### ISSUE TITLE
Support dart 1.13 (re: SecureSocket)

### ISSUE THREAD

**Issue by srawlins** [dart-lang/http_server#31]
http_server needs to be updated here and there to support Dart 1.13:
- [test/utils.dart](https://github.com/dart-lang/http_server/blob/master/test/utils.dart#L298) needs to not call SecureSocket.initialize.
- Other problems in tests, I think.

Dart has provided a [migration guide](https://www.dartlang.org/server/tls-ssl.html). Um... it might be out of date though. SecureSocket.initialize [doesn't exist](https://api.dartlang.org/1.13.0-dev.7.10/dart-io/SecureSocket-class.html) anymore.

**Comment by kevmoo** [comment]
Great call on the migration guide, @srawlins – opened a bug on the site – https://github.com/dart-lang/www.dartlang.org/issues/1520

**Comment by sgjesse** [comment]
Fixed in 3ed8c55b96fad5854a6d0bc419c446ee0f84303a.
