### ISSUE TITLE
Incorrect use of `package:test`

### ISSUE THREAD

**Issue by grouma** [dart-lang/http_server#51]
In the various test files, several `expect` clauses are created but there is no call to `test`. Thus the tests will always pass as no tests are actually run.

cc @leafpetersen

**Comment by kevmoo** [comment]
Can you point to some examples?

**Comment by grouma** [comment]
Take a look at
https://github.com/dart-lang/http_server/blob/master/test/http_multipart_test.dart#L91

There are a handful of `expect` cases but no call to `test`.
