### ISSUE TITLE
VirtualDirectory consume a lot of memory when serve very large file

### ISSUE THREAD

**Issue by cvbni** [dart-lang/http_server#59]
The server side(running in my android phone):
Future main() async {
  VirtualDirectory staticFiles = VirtualDirectory('/storage/emulated/0/')..allowDirectoryListing = true;
  var serverRequests =
      await HttpServer.bind('0.0.0.0', 4046);
  await for (var request in serverRequests) {
    staticFiles.serveFile(targetFile, request);
  }
----------------------------------
The client side:
PC Firefox

The server side consumed a lot of memory then forced to exit when I downloaded a large file(>4GB)

**Comment by zengkid** [comment]
@cvbni Have you fixed the issue? could you share?

**Comment by cvbni** [comment]
> 
> 
> @cvbni Have you fixed the issue? could you share?

No,
Because HttpResponse don't support for chunked responses.
We can't solve this issue.
https://github.com/dart-lang/sdk/issues/26283
